version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=persurl
      - POSTGRES_USER=persurl
      - POSTGRES_PASSWORD=persurl
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    profiles: ["pgadmin"]
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5454:80"

volumes:
  db:
