openapi: 3.0.3
info:
  title: PersURL
  description: Application to manage and resolve [PURL](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator) links.
  version: v1
  license:
    name: MIT

servers:
  - url: "http://localhost"

tags:
  - name: Resolve
    description: Resolution of PURLs
  - name: Admin
    description: Manage PURLs
  - name: System
    description: Endpoints for interacting / managing the overall system

security: []

paths:
  /s/health:
    get:
      operationId: getHealth
      summary: Check if service is healthy
      tags: [System]
      responses:
        200:
          description: Service is healthy
        500:
          description: Service is not healthy

  /s/stats/public:
    get:
      operationId: getPublicStats
      summary: Get public stats about this system
      tags: [System]
      responses:
        200:
          description: Returns stats
          content:
            application/json:
              schema:
                type: object
                properties:
                  domains_total:
                    type: integer
                  purls_total:
                    type: integer

  /r/{domain}/{name}:
    get:
      operationId: resolvePURL
      summary: Resolve a PURL
      tags: [Resolve]
      parameters:
        - $ref: '#/components/parameters/domain'
        - $ref: '#/components/parameters/name'
      responses:
        302:
          description: PURL resolved, use the `Location` header to navigate to the target.
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          description: PURL not resolved, it probably does not exist.

  /a/domains/{domain}/purls/{name}:
    put:
      operationId: savePURL
      summary: Create or update a PURL
      tags: [Admin]
      parameters:
        - $ref: '#/components/parameters/domain'
        - $ref: '#/components/parameters/name'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                target:
                  type: string
                  description: The target URL to redirect to.
              required:
                - target
      responses:
        200:
          description: PURL created or updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  path:
                    type: string
                    example: /r/your-domain/your-purl
        400:
          $ref: "#/components/responses/BadRequest"

  /a/domains/{domain}:
    post:
      operationId: createDomain
      summary: Create a domain
      tags: [Admin]
      parameters:
        - $ref: '#/components/parameters/domain'
      responses:
        204:
          description: Domain created.
        400:
          $ref: "#/components/responses/BadRequest"

components:
  parameters:
    domain:
      name: domain
      in: path
      description: The domain of the PURL.
      required: true
      schema:
        $ref: '#/components/schemas/Named'
    name:
      name: name
      in: path
      description: The name of the PURL.
      required: true
      schema:
        $ref: '#/components/schemas/Named'

  responses:
    BadRequest:
      description: Bad request, see response body for details.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorList'

  schemas:
    ErrorList:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
            example: Something went wrong

    Named:
      type: string
      description: A name safe for URL usage
      pattern: "^[a-zA-Z0-9\\._-]+$"
