name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PERSURL_DB_DSN: postgresql://persurl:persurl@localhost:5432/persurl?sslmode=disable
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Lint Code
      run: go vet -v ./...
    - name: Lint API Spec
      run: npx @redocly/cli lint api/openapi.yml

    - name: Run database
      run: docker compose up --quiet-pull -d && sleep 5
    - name: Install Test Runner
      run: go install github.com/mfridman/tparse@latest
    - name: Test
      run: set -o pipefail && go test -json -v ./... | tparse -all

    - name: Build
      run: go build -v ./...

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: docker build --target runtime .

  test-load:
    runs-on: ubuntu-latest
    env:
      TEST_LOAD: 1
      PERSURL_DB_DSN: postgresql://persurl:persurl@localhost:5432/persurl?sslmode=disable
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run database
      run: docker compose up --quiet-pull -d && sleep 5
    - name: Install Test Runner
      run: go install github.com/mfridman/tparse@latest
    - name: Test
      run: set -o pipefail && go test -json tests/http_load_test.go | tparse -all
